---
- hosts: 127.0.0.1
  tasks:

#  - name: Update Brew and Upgrade Packages
#    homebrew:
#      update_homebrew: yes
#      upgrade_all: yes

  - name: Install apps with homebrew
    homebrew: name={{ item }} state=present
    with_items:
      - wget
      - git
      - kubectl
      - kubernetes-helm
      - zsh
      - zsh-completions
      - p7zip
      - node
      - go
      - jq

  - name: Install cask packagses
    homebrew_cask: name={{ item }} state=present
    with_items:
      - iterm2
      - google-chrome
      - dropbox
      - webstorm
      - intellij-idea
      - pycharm-ce
      - docker
      - minikube
      - VirtualBox
      - opera
      #- 1password
      - lastpass
      - microsoft-office
      - xmind
      - minikube
      - ngrok
      - anaconda
      - java
      - slack
      - tunnelblick

  - name: Install Media Packages
    homebrew_cask: name={{ item }} state=present
    with_items:
      - kodi

  - name: Install Pip Packages
    pip: name={{ item }} state=present
    with_items:
      - glances
      - apache-airflow
