---
- hosts: 127.0.0.1
  tasks:

#  - name: Update Brew and Upgrade Packages
#    homebrew:
#      update_homebrew: yes
#      upgrade_all: yes

  - name: Install apps with homebrew
    homebrew: name={{ item }} state=present
    with_items:
      - wget
      - git
      - kubectl
      - node
      - go
      - jq
      - k3d

  - name: Install Base Cask packagses
    homebrew_cask: name={{ item }} state=present
    with_items:
      - iterm2
      - google-chrome
      - dropbox
      - webstorm
      - intellij-idea
      - pycharm-ce
      - docker
      - anaconda
      - java
      - slack
      - atom
      - whatsapp
      - microsoft-teams
      - little-snitch
      - visual-studio-code
      - android-studio
      - notion
      - figma
      - evernote
      - google-drive-file-stream
      - microsoft-office

  - name: Install GTD Cask packagses
    homebrew_cask: name={{ item }} state=present
    with_items:
      - todoist


  - name: Install Pip Packages
    pip: name={{ item }} state=present
    with_items:
      - glances
