---
- hosts: 127.0.0.1
  tasks:

#  - name: Update Brew and Upgrade Packages
#    homebrew:
#      update_homebrew: yes
#      upgrade_all: yes

  - name: Install Core tools with homebrew
    homebrew: name={{ item }} state=present
    with_items:
      - wget
      - git
      - node
      - go
      - jq
      - zsh
      - terraform
      - yarn
      - nvm

  - name: Install K8S tools with homebrew
    homebrew: name={{ item }} state=present
    with_items:
      - kubectl
      - k3d
      - helm
      - knative/client/kn
      - ubuntu/microk8s/microk8s
      - derailed/k9s/k9s
      - minikube
      - crc
      - skaffold
      
  - name: Install Base Cask packagses
    homebrew_cask: name={{ item }} state=present
    with_items:
      - iterm2
      - google-chrome
      - dropbox
      - webstorm
      - intellij-idea
      - pycharm-ce
      - docker
      - anaconda
      - java
      - slack
      - atom
      - whatsapp
      - microsoft-teams
      - little-snitch
      - visual-studio-code
      - android-studio
      - notion
      - figma
      - evernote
      - google-drive-file-stream
      - microsoft-office
      - sketch
      - spotify
      - coconutbattery